os: windows
language: cpp
solution: Ball-Sort-Puzzle-Solver.sln
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  #- choco install dotnetcore-sdk
  #- choco install paket --pre
  - choco install nuget.commandline --pre 
  #- dotnet restore
  #- paket restore
  - nuget restore Ball-Sort-Puzzle-Solver.sln
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe -p:Configuration=Release -p:Platform=x64 Ball-Sort-Puzzle-Solver/Ball-Sort-Puzzle-Solver.vcxproj
  #- paket init
  #- paket add Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn --version 1.8.1
  #- dotnet add package Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn --version 1.8.1.3
  - MSBuild.exe -p:Configuration=Release -p:Platform=x64 Ball-Sort-Puzzle-Solver-Tester/Ball-Sort-Puzzle-Solver-Tester.vcxproj
  - xcopy ./tests ./Ball-Sort-Puzzle-Solver-Tester/x64/tests /E /H /C /I
  - mv ./tests ./Ball-Sort-Puzzle-Solver-Tester/x64/tests
  - ./Ball-Sort-Puzzle-Solver-Tester/x64/Release/Ball-Sort-Puzzle-Solver-Tester.exe
  